language: node_js
node_js:
env: CXX=g++-4.9
addons:
  apt:
    packages: g++-4.9
install:
- npm install
- gulp --prod
branches:
  only:
    - master
    - develop
after_success:
- git remote add deploy ssh://$VPS_USER@$VPS_IP_ADDRESS$VPS_PATH
- git push deploy $TRAVIS_BRANCH
before_install:
- echo -e "Host $VPS_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_664ac0a2c83a_key -iv $encrypted_664ac0a2c83a_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
